// <auto-generated />
using CarListApp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListApp.Api.Migrations
{
    [DbContext(typeof(CarListDbContext))]
    partial class CarListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CarListApp.Api.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Toyota",
                            Model = "Corolla",
                            Vin = "JT4BG22K6V000001"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Honda",
                            Model = "Civic",
                            Vin = "2HGES16555H000002"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Ford",
                            Model = "Mustang",
                            Vin = "1FAFP404X1F000003"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Chevrolet",
                            Model = "Impala",
                            Vin = "2G1WF52E659000004"
                        },
                        new
                        {
                            Id = 5,
                            Make = "Nissan",
                            Model = "Altima",
                            Vin = "1N4AL11D75C000005"
                        },
                        new
                        {
                            Id = 6,
                            Make = "BMW",
                            Model = "320",
                            Vin = "WBA3A5C50DF000006"
                        },
                        new
                        {
                            Id = 7,
                            Make = "Audi",
                            Model = "A4",
                            Vin = "WAUDF78E37A000007"
                        },
                        new
                        {
                            Id = 8,
                            Make = "Mercedes-Benz",
                            Model = "C-Class",
                            Vin = "WDBRF40JX3F000008"
                        },
                        new
                        {
                            Id = 9,
                            Make = "Volkswagen",
                            Model = "Jetta",
                            Vin = "3VW2K7AJ5DM000009"
                        },
                        new
                        {
                            Id = 10,
                            Make = "Subaru",
                            Model = "Impreza",
                            Vin = "JF1GPAL69DH000010"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
